name: release

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: v1.17

      - name: Build
        run: |
          go build -ldflags="-X main.tagName=$(git describe --tags --abbrev=0) -X main.sha=$(git rev-parse --short HEAD) -H=windowsgui" -o dist/

      - uses: ncipollo/release-action@v1
        with:
          artifacts: "dist/*.exe"
          token: ${{ secrets.GITHUB_TOKEN }}
